name: node_nseg7_NN
n_seg: 7

# Dataset
train_trajs:
  - 2
  - 4
  - 6
  - 9
  - 14
  - 15
  - 16
  - 18
  - 19

data_seed: 812
batch_size: 64
rollout_length: 250
n_epochs: 25

# Dynamics model
model_seed: 42
encoder:
  type: NN
  width: 128
  depth: 2
  activation: tanh

dynamics:
  type: DiscretizedNODE
  n_u: 18
  width: 128
  depth: 2
  activation: relu6
  integrator:
    dt: 0.004
    rtol: 1.e-5
    atol: 1.e-5

decoder:
  type: NN
  n_y: 6
  width: 128
  depth: 2
  activation: tanh

# Optimizer
optimizer: adamw # rmsprop sgd
learning_rate_scheduler: polynomial 
initial_learning_rate: 0.002
transition_epochs: 25
final_learning_rate: 1.E-4
polynomial_power: 0.5
weight_decay: 0.01

# Cost function weights
q_rfem_l2: 0.0
dq_rfem_l2: 0.0
