name: resnet_7seg_FFK
n_seg: 7

# Dynamics model
model_seed: 42
encoder:
  type: PINN
  width: 128
  depth: 2
  activation: tanh

dynamics:
  type: ResNet
  n_u: 18
  width: 256
  depth: 3
  activation: tanh

decoder:
  type: FK
  n_y: 6


# Dataset
train_trajs:
  - 1
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 16
  - 18
  - 19

data_seed: 812
batch_size: 64
rollout_length: 250
n_epochs: 40

# Optimizer
optimizer: adamw # rmsprop sgd
learning_rate_scheduler: polynomial 
initial_learning_rate: 0.002
transition_epochs: 25
final_learning_rate: 1.E-4
polynomial_power: 1
weight_decay: 0.0001

# Cost function weights
q_rfem_l2: 0.5
dq_rfem_l2: 0.05
