name: resnet_7seg_LFK
n_seg: 7

# Dynamics model
model_seed: 42
encoder:
  type: PINN
  width: 128
  depth: 2
  activation: tanh

dynamics:
  type: ResNet
  n_u: 18
  width: 256
  depth: 3
  activation: tanh

decoder:
  type: TrainableFKDecoder
  n_y: 6


# Dataset
train_trajs:
  - 2
  - 4
  - 6
  - 9
  - 14
  - 15
  - 16
  - 18
  - 19

data_seed: 812
batch_size: 64
rollout_length: 250
n_epochs: 25

# Optimizer
optimizer: adamw # rmsprop sgd
learning_rate_scheduler: polynomial 
initial_learning_rate: 0.002
final_learning_rate: 0.00001
polynomial_power: 1.0
weight_decay: 0.01

# Cost function weights
q_rfem_l2: 0.1
dq_rfem_l2: 0.01
