name: rnn_nseg10_LFK
n_seg: 10

# Dynamics model
model_seed: 42
encoder:
  type: PINN
  width: 64
  depth: 3
  activation: tanh

dynamics:
  type: RNN
  n_u: 18

decoder:
  type: TrainableFKDecoder
  n_y: 6


# Dataset
train_trajs:
  - 1
  - 7
  - 13
  - 16
  - 18
  - 19

data_seed: 812
batch_size: 64
rollout_length: 250
n_epochs: 30


# Optimizer
optimizer: adamw
learning_rate_scheduler: polynomial
initial_learning_rate: 0.002
final_learning_rate: 0.00001
polynomial_power: 1
weight_decay: 0.0001

# Loss function
q_rfem_l2: 1.0
dq_rfem_l2: 0.0
