name: rnn_2seg_LFK
n_seg: 2

# Dynamics model
model_seed: 42
encoder:
  type: PINN
  width: 64
  depth: 2
  activation: tanh

dynamics:
  type: RNN
  n_u: 18


decoder:
  type: TrainableFKDecoder
  n_y: 6


# Dataset
train_trajs:
  - 2
  - 4
  - 6
  - 9
  - 14
  - 15
  - 16
  - 18
  - 19

data_seed: 812
batch_size: 64
rollout_length: 250
n_epochs: 25

# Optimizer
optimizer: adamw
learning_rate_scheduler: polynomial
initial_learning_rate: 0.004
final_learning_rate: 0.00001
polynomial_power: 0.5
weight_decay: 0.001

# Loss function weights
q_rfem_l2: 1.0
dq_rfem_l2: 0.1