name: rnn_20seg_NN
n_seg: 20

# Dynamics model
model_seed: 42
encoder:
  type: NN
  width: 32
  depth: 3
  activation: tanh

dynamics:
  type: RNN
  n_u: 18

decoder:
  type: NN
  n_y: 6
  width: 128
  depth: 3
  activation: tanh

# Dataset
train_trajs:
  - 1
  - 4
  - 6
  - 9
  - 13
  - 14
  - 16
  - 18
  - 19


data_seed: 812
batch_size: 64
rollout_length: 250
n_epochs: 40

# Optimizer
optimizer: adamw # rmsprop sgd
learning_rate_scheduler: polynomial 
initial_learning_rate: 0.002
transition_epochs: 25
final_learning_rate: 0.0001
polynomial_power: 0.5
weight_decay: 0.0001

# Cost function weights
q_rfem_l2: 0.0
dq_rfem_l2: 0.0
