name: rnn_10seg_FFK
n_seg: 10

# Dynamics model
model_seed: 42
encoder:
  type: PINN
  width: 128
  depth: 3
  activation: tanh

dynamics:
  type: RNN
  n_u: 18

decoder:
  type: FK
  n_y: 6


# Dataset
train_trajs:
  - 1
  - 3
  - 5
  - 7
  - 9
  - 13
  - 14
  - 16
  - 18
  - 19

data_seed: 812
batch_size: 64
rollout_length: 250
n_epochs: 30


# Optimizer
optimizer: adamw
learning_rate_scheduler: polynomial
initial_learning_rate: 0.002
transition_epochs: 25
final_learning_rate: 1.E-4
polynomial_power: 1.0
weight_decay: 0.0001

# Loss function
q_rfem_l2: 0.1
dq_rfem_l2: 0.01
