name: PN_node_7seg_LFK
DLO: pool-noodle
n_seg: 7

# Dataset
train_trajs:
  - 1
  - 2
  - 3
  - 5
  - 6
  - 7
val_trajs: 
  - 4
test_trajs: 
  - 8

data_seed: 812
batch_size: 64
rollout_length: 250
n_epochs: 15

# Rollout legnth scheduler
rollout_length_scheduler:
  init_value: 0.1
  boundaries:
    - 1
  scales:
    - 10

# Dynamics model
model_seed: 42
encoder:
  type: PINN
  width: 128
  depth: 1
  activation: relu6

dynamics:
  type: DiscretizedNODE
  n_u: 18
  width: 64
  depth: 1
  activation: tanh
  integrator:
    dt: 0.004
    rtol: 1.e-3
    atol: 1.e-3

decoder:
  type: TrainableFKDecoder
  n_y: 6

# Optimizer
optimizer: adabelief # rmsprop sgd
learning_rate_scheduler: polynomial 
initial_learning_rate: 2.E-3
transition_epochs: 10
final_learning_rate: 1.E-4
polynomial_power: 1.0
weight_decay: 1.E-4

# Cost function weights
q_rfem_l2: 0.4
dq_rfem_l2: 0.04
