name: PN_rnn_20seg_LFK
DLO: pool-noodle
n_seg: 20

# Dynamics model
model_seed: 42
encoder:
  type: PINN
  width: 128
  depth: 2
  activation: relu6

dynamics:
  type: RNN
  n_u: 18

decoder:
  type: TrainableFKDecoder
  n_y: 6

# Dataset
train_trajs:
  - 1
  - 2
  - 3
  - 5
  - 6
  - 7
val_trajs: 
  - 4
test_trajs: 
  - 8

data_seed: 812
batch_size: 64
rollout_length: 250
n_epochs: 40

# Rollout legnth scheduler
rollout_length_scheduler:
  init_value: 0.1
  boundaries:
    - 5
    - 30
  scales:
    - 5
    - 2

# Optimizer
optimizer: adabelief # rmsprop sgd
learning_rate_scheduler: polynomial 
initial_learning_rate: 5.E-3
transition_epochs: 30
final_learning_rate: 1.E-3
polynomial_power: 0.5
weight_decay: 1.E-3

# Cost function weights
q_rfem_l2: 0.4
dq_rfem_l2: 0.04
