name: PN_resnet_7seg_LFK
DLO: pool-noodle
n_seg: 7

# Dynamics model
model_seed: 42
encoder:
  type: PINN
  width: 128
  depth: 2
  activation: relu6

dynamics:
  type: ResNet
  n_u: 18
  width: 128
  depth: 2
  activation: tanh

decoder:
  type: TrainableFKDecoder
  n_y: 6


# Dataset
train_trajs:
  - 1
  - 2
  - 3
  - 5
  - 6
  - 7
val_trajs: 
  - 4
test_trajs: 
  - 8

data_seed: 812
batch_size: 64
rollout_length: 250
n_epochs: 55

# Rollout legnth scheduler
rollout_length_scheduler:
  init_value: 0.1
  boundaries:
    - 18
  scales:
    - 10

# Optimizer
optimizer: adabelief # rmsprop sgd
learning_rate_scheduler: polynomial
initial_learning_rate: 1.E-3
transition_epochs: 40
final_learning_rate: 2.E-5
polynomial_power: 0.5
weight_decay: 1.E-3

# Loss function
q_rfem_l2: 0.4
dq_rfem_l2: 0.04
