name: resnet_7seg_LFK
DLO: aluminium-rod
n_seg: 7

# Dynamics model
model_seed: 42
encoder:
  type: PINN
  width: 128
  depth: 2
  activation: tanh

dynamics:
  type: ResNet
  n_u: 18
  width: 256
  depth: 2
  activation: tanh

decoder:
  type: TrainableFKDecoder
  n_y: 6


# Dataset
train_trajs:
  - 1
  - 4
  - 6
  - 9
  - 13
  - 14
  - 16
  - 18
  - 19
test_trajs: 
  - 2
  - 5
  - 17


data_seed: 812
batch_size: 64
rollout_length: 250
n_epochs: 40

# Rollout legnth scheduler
rollout_length_scheduler:
  init_value: 0.1
  boundaries:
    - 10
  scales:
    - 10

# Optimizer
optimizer: adamw # rmsprop sgd
learning_rate_scheduler: polynomial 
initial_learning_rate: 0.002
transition_epochs: 25
final_learning_rate: 0.00001
polynomial_power: 1.0
weight_decay: 0.01

# Cost function weights
q_rfem_l2: 1.0
dq_rfem_l2: 0.1
