name: rnn_20seg_FFK
n_seg: 20

# Dynamics model
model_seed: 42
encoder:
  type: PINN
  width: 128
  depth: 2
  activation: tanh

dynamics:
  type: RNN
  n_u: 18

decoder:
  type: FK
  n_y: 6


# Dataset
train_trajs:
  - 1
  - 4
  - 6
  - 9
  - 13
  - 14
  - 16
  - 18
  - 19

data_seed: 812
batch_size: 64
rollout_length: 250
n_epochs: 40

# Rollout legnth scheduler
rollout_length_scheduler:
  init_value: 0.1
  boundaries:
    - 12
  scales:
    - 10

# Optimizer
optimizer: adamw
learning_rate_scheduler: polynomial
initial_learning_rate: 0.002
final_learning_rate: 1.E-4
transition_epochs: 25
polynomial_power: 1.0
weight_decay: 0.0001

# Loss function
q_rfem_l2: 1.0
dq_rfem_l2: 0.1