name: rnn_2seg_LFK_rss
DLO: aluminium-rod
n_seg: 2

# Dynamics model
model_seed: 42
encoder:
  type: PINN
  width: 32
  depth: 2
  activation: tanh

dynamics:
  type: RNN
  n_u: 18

decoder:
  type: TrainableFKDecoder
  n_y: 6


# Dataset
train_trajs:
  - 16

test_trajs: 
  - 13
  - 15
  - 17
  - 18

data_seed: 812
batch_size: 64
rollout_length: 250
n_epochs: 40

# Rollout legnth scheduler
rollout_length_scheduler:
  init_value: 0.1
  boundaries:
    - 5
    - 15
  scales:
    - 2
    - 5

# Optimizer
optimizer: adamw
learning_rate_scheduler: polynomial
initial_learning_rate: 0.002
final_learning_rate: 0.00005
transition_epochs: 25
polynomial_power: 0.5
weight_decay: 0.0001

# Loss function
q_rfem_l2: 1.0
dq_rfem_l2: 0.1
