name: rnn_7seg_NN
DLO: aluminium-rod
n_seg: 7

# Dynamics model
model_seed: 42
encoder:
  type: NN
  width: 32
  depth: 3
  activation: tanh

dynamics:
  type: RNN
  n_u: 18

decoder:
  type: NN
  n_y: 6
  width: 128
  depth: 3
  activation: tanh

# Dataset
train_trajs:
  - 1
  - 4
  - 6
  - 9
  - 13
  - 14
  - 16
  - 18
  - 19
test_trajs: 
  - 2
  - 5
  - 17

data_seed: 812
batch_size: 64
rollout_length: 250
n_epochs: 25

# Rollout legnth scheduler
rollout_length_scheduler:
  init_value: 0.1
  boundaries:
    - 4
    - 12
  scales:
    - 5
    - 2

# Optimizer
optimizer: adamw # rmsprop sgd
learning_rate_scheduler: polynomial 
initial_learning_rate: 0.002
transition_epochs: 25
final_learning_rate: 0.0001
polynomial_power: 0.5
weight_decay: 0.0001

# Cost function weights
q_rfem_l2: 0.0
dq_rfem_l2: 0.0
